{
  "hash": "c60fe3aa332a290c2ed3faf40ccdd18b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Hands-on Exercise 4: Spatial Weights and Applications\"\nauthor: \"JUNCHEN LI\"\ndate: \"September 16, 2026\"\ndate-modified: \"last-modified\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: true\n    code-summary: \"Show code\"\n    code-tools: true\neditor: source\nexecute:\n  echo: true\n  warning: false\n  message: false\n  freeze: auto\n---\n\n# Overview\n\nThis exercise follows [Chapter 8: Spatial Weights and Applications](https://r4gdsa.netlify.app/chap08.html). It uses Hunan county boundaries and the **2012** development indicators to explore how different definitions of a neighbour affect spatial summaries. The workflow covers contiguity, distance bands, nearest neighbours, inverse-distance weights and four spatial-lag operations.\n\n# 1 Data and reproducibility\n\nThe files were downloaded from the instructor's [ISSS626-AY2026-27Aug repository](https://github.com/tskam/ISSS626-AY2026-27Aug/tree/966eea6df498b38f10bc209d07a922f4d87b95d9/lesson/Lesson04/data) on 16 September 2026. The download script pins the repository commit, so future changes to the online course will not silently replace this input. The indicator year remains 2012; it is not the year of download. No newer statistical series has been substituted.\n\n| Local file | Purpose |\n|---|---|\n| `data/geospatial/Hunan.shp` and companion files | County polygons and identifiers |\n| `data/aspatial/Hunan_2012.csv` | County development indicators for 2012 |\n| `data/download-data.R` | Retrieve the pinned source files into an empty data location |\n| `data/download-manifest.txt` | Source URLs, retrieval date and raw-file checksums |\n\n## Loading packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(sf)\nlibrary(spdep)\nlibrary(tmap)\nlibrary(dplyr)\nlibrary(readr)\nlibrary(knitr)\ntmap_mode(\"plot\")\n```\n:::\n\n\n## Importing and checking the join\n\nThe join uses an explicit county key. Duplicate keys or unmatched counties would invalidate the positional relationship between observations and weights, so the checks stop execution rather than silently continuing.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan_boundary <- st_read(\"data/geospatial/Hunan.shp\", quiet = TRUE)\nhunan2012 <- read_csv(\"data/aspatial/Hunan_2012.csv\", show_col_types = FALSE)\nraw_files <- c(list.files(\"data/geospatial\", full.names = TRUE),\n               \"data/aspatial/Hunan_2012.csv\")\nraw_md5 <- tools::md5sum(raw_files)\nstopifnot(nrow(hunan_boundary) == 88L, nrow(hunan2012) == 88L,\n          !anyDuplicated(hunan_boundary$County),\n          !anyDuplicated(hunan2012$County),\n          setequal(hunan_boundary$County, hunan2012$County),\n          all(st_is_valid(hunan_boundary)),\n          !any(st_is_empty(hunan_boundary)),\n          st_is_longlat(hunan_boundary))\nhunan <- left_join(hunan_boundary,\n                   select(hunan2012, County, GDPPC),\n                   by = \"County\", relationship = \"one-to-one\") |>\n  select(NAME_2, ID_3, NAME_3, ENGTYPE_3, County, GDPPC)\nstopifnot(identical(hunan$County, hunan_boundary$County),\n          all(is.finite(hunan$GDPPC)), all(hunan$GDPPC > 0))\ndata.frame(Counties = nrow(hunan), Indicator_year = 2012,\n           Missing_GDPPC = sum(is.na(hunan$GDPPC)),\n           Valid_geometries = sum(st_is_valid(hunan))) |> kable()\n```\n\n::: {.cell-output-display}\n\n\n| Counties| Indicator_year| Missing_GDPPC| Valid_geometries|\n|--------:|--------------:|-------------:|----------------:|\n|       88|           2012|             0|               88|\n\n\n:::\n\n```{.r .cell-code}\nhead(st_drop_geometry(hunan)) |> kable()\n```\n\n::: {.cell-output-display}\n\n\n|NAME_2  |  ID_3|NAME_3  |ENGTYPE_3   |County  | GDPPC|\n|:-------|-----:|:-------|:-----------|:-------|-----:|\n|Changde | 21098|Anxiang |County      |Anxiang | 23667|\n|Changde | 21100|Hanshou |County      |Hanshou | 20981|\n|Changde | 21101|Jinshi  |County City |Jinshi  | 34592|\n|Changde | 21102|Li      |County      |Li      | 24473|\n|Changde | 21103|Linli   |County      |Linli   | 25554|\n|Changde | 21104|Shimen  |County      |Shimen  | 27137|\n\n\n:::\n:::\n\n\n# 2 Mapping the indicator\n\nThe identifier map establishes the spatial units. The second map displays the supplied GDP-per-capita field. Values retain the source scale; no inflation adjustment or currency conversion is applied. The maps use the current tmap 4 interface.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncounty_map <- tm_shape(hunan) +\n  tm_polygons(fill = \"#edf2f7\", col = \"#64748b\", lwd = 0.5) +\n  tm_text(\"NAME_3\", size = 0.45) +\n  tm_title(\"County boundaries\", size = 1) +\n  tm_layout(frame = FALSE)\nindicator_map <- tm_shape(hunan) +\n  tm_polygons(fill = \"GDPPC\",\n              fill.scale = tm_scale_intervals(style = \"quantile\", n = 5,\n                                               values = \"brewer.yl_or_br\"),\n              fill.legend = tm_legend(title = \"GDPPC (2012)\"),\n              col = \"white\", lwd = 0.5) +\n  tm_title(\"GDP per capita\", size = 1) +\n  tm_layout(frame = FALSE, legend.outside = TRUE)\ntmap_arrange(county_map, indicator_map, ncol = 2)\n```\n\n::: {.cell-output-display}\n![Hunan county identifiers and the supplied GDPPC indicator, 2012.](Hands-on_Ex0401_files/figure-html/fig-county-indicator-1.png){#fig-county-indicator width=1152}\n:::\n:::\n\n\n# 3 Contiguity-based neighbours\n\nQueen contiguity accepts a shared boundary point; rook contiguity requires more than a single shared point. These relationships describe topology, not travel time. A county outside the supplied Hunan layer cannot appear in either neighbour list. See the [poly2nb documentation](https://r-spatial.github.io/spdep/reference/poly2nb.html).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqueen_nb <- poly2nb(hunan, queen = TRUE, row.names = hunan$County)\nrook_nb <- poly2nb(hunan, queen = FALSE, row.names = hunan$County)\nnb_summary <- function(nb, label) {\n  data.frame(Method = label, Counties = length(nb),\n             Directed_links = sum(card(nb)),\n             Minimum_neighbours = min(card(nb)),\n             Mean_neighbours = mean(card(nb)),\n             Maximum_neighbours = max(card(nb)),\n             Isolates = sum(card(nb) == 0),\n             Weak_components = n.comp.nb(make.sym.nb(nb))$nc)\n}\nbind_rows(nb_summary(queen_nb, \"Queen\"),\n          nb_summary(rook_nb, \"Rook\")) |> kable(digits = 2)\n```\n\n::: {.cell-output-display}\n\n\n|Method | Counties| Directed_links| Minimum_neighbours| Mean_neighbours| Maximum_neighbours| Isolates| Weak_components|\n|:------|--------:|--------------:|------------------:|---------------:|------------------:|--------:|---------------:|\n|Queen  |       88|            448|                  1|            5.09|                 11|        0|               1|\n|Rook   |       88|            440|                  1|            5.00|                 10|        0|               1|\n\n\n:::\n\n```{.r .cell-code}\nstopifnot(all(card(queen_nb) >= card(rook_nb)),\n          all(card(queen_nb) > 0))\n```\n:::\n\n\nThe downloaded layer produces **448 queen links** and **440 rook links**, counted directionally. A reciprocal connection contributes two links, so these counts are not counts of unique undirected county pairs.\n\n## Inspecting one county\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanxiang <- match(\"Anxiang\", hunan$County)\nstopifnot(!is.na(anxiang))\nanxiang_neighbours <- queen_nb[[anxiang]]\ndata.frame(County = hunan$County[anxiang_neighbours],\n           GDPPC = hunan$GDPPC[anxiang_neighbours]) |> kable()\n```\n\n::: {.cell-output-display}\n\n\n|County  | GDPPC|\n|:-------|-----:|\n|Hanshou | 20981|\n|Jinshi  | 34592|\n|Li      | 24473|\n|Nan     | 21311|\n|Taoyuan | 22879|\n\n\n:::\n:::\n\n\n## Preparing representative points\n\nPolygon centroids are computed in UTM zone 49N and transformed back to longitude/latitude. Using a projected geometry avoids treating degrees as planar distance units when constructing centroids. These are geometric representatives, not county capitals, and centroids need not lie inside a concave polygon. The raw boundary remains unchanged.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan_projected <- st_transform(hunan, 32649)\ncentroids <- st_centroid(st_geometry(hunan_projected)) |> st_transform(4326)\ncoords <- st_coordinates(centroids)\nstopifnot(!anyDuplicated(as.data.frame(coords)), all(is.finite(coords)))\nplot_network <- function(nb, title, colour = \"#0072B2\") {\n  plot(st_geometry(hunan), col = \"#f8fafc\", border = \"#94a3b8\", main = title)\n  plot(nb, coords, add = TRUE, col = colour, pch = 19, cex = 0.45)\n}\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(1, 2), mar = c(1, 1, 3, 1))\nplot_network(queen_nb, \"Queen contiguity\")\nplot_network(rook_nb, \"Rook contiguity\", \"#D55E00\")\npar(mfrow = c(1, 1))\n```\n\n::: {.cell-output-display}\n![Queen and rook connectivity between county representative points.](Hands-on_Ex0401_files/figure-html/fig-contiguity-1.png){#fig-contiguity width=1152}\n:::\n:::\n\n\n# 4 Distance-based neighbours\n\nAll neighbour searches and distance measurements below explicitly use `longlat = TRUE`, returning great-circle distances in kilometres. The chapter's nearest-neighbour search omits this flag even though the coordinates are longitude/latitude. Together with the projected-centroid calculation, this makes exact distance outputs here potentially different from the chapter's printed results. No value is forced to match the textbook.\n\n## Checking the distance threshold\n\nThe largest nearest-neighbour distance provides a threshold that avoids isolated counties. Having at least one neighbour does **not** guarantee that the complete graph is connected, so components are checked separately. The chapter's 62 km band is retained for comparison. [Distance-band documentation](https://r-spatial.github.io/spdep/reference/dnearneigh.html).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnearest1 <- knn2nb(knearneigh(coords, k = 1, longlat = TRUE),\n                   row.names = hunan$County)\nnearest_distances <- unlist(nbdists(nearest1, coords, longlat = TRUE))\nminimum_band_km <- max(nearest_distances)\nrounded_band_km <- ceiling(minimum_band_km)\ndistance_min_nb <- dnearneigh(coords, 0, rounded_band_km,\n                             longlat = TRUE, row.names = hunan$County)\ndistance62_nb <- dnearneigh(coords, 0, 62,\n                           longlat = TRUE, row.names = hunan$County)\nstopifnot(all(card(distance_min_nb) > 0), all(card(distance62_nb) > 0))\ndata.frame(Minimum_1NN_km = min(nearest_distances),\n           Maximum_1NN_km = minimum_band_km,\n           Rounded_band_km = rounded_band_km) |> kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n| Minimum_1NN_km| Maximum_1NN_km| Rounded_band_km|\n|--------------:|--------------:|---------------:|\n|          24.79|         58.357|              59|\n\n\n:::\n\n```{.r .cell-code}\nbind_rows(nb_summary(distance_min_nb, paste(rounded_band_km, \"km band\")),\n          nb_summary(distance62_nb, \"62 km band\")) |> kable(digits = 2)\n```\n\n::: {.cell-output-display}\n\n\n|Method     | Counties| Directed_links| Minimum_neighbours| Mean_neighbours| Maximum_neighbours| Isolates| Weak_components|\n|:----------|--------:|--------------:|------------------:|---------------:|------------------:|--------:|---------------:|\n|59 km band |       88|            298|                  1|            3.39|                  6|        0|               2|\n|62 km band |       88|            324|                  1|            3.68|                  6|        0|               1|\n\n\n:::\n:::\n\n\n## Six nearest neighbours\n\nEach county selects six neighbours, but the sixth neighbour can be much farther away in sparsely spaced areas. Selection need not be reciprocal: if A selects B, B may not select A. The graph is left directed rather than silently symmetrised. [Nearest-neighbour documentation](https://r-spatial.github.io/spdep/reference/knearneigh.html).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nknn6_nb <- knn2nb(knearneigh(coords, k = 6, longlat = TRUE),\n                  row.names = hunan$County, sym = FALSE)\nstopifnot(all(card(knn6_nb) == 6L))\nnb_summary(knn6_nb, \"Six nearest neighbours\") |> kable(digits = 2)\n```\n\n::: {.cell-output-display}\n\n\n|Method                 | Counties| Directed_links| Minimum_neighbours| Mean_neighbours| Maximum_neighbours| Isolates| Weak_components|\n|:----------------------|--------:|--------------:|------------------:|---------------:|------------------:|--------:|---------------:|\n|Six nearest neighbours |       88|            528|                  6|               6|                  6|        0|               1|\n\n\n:::\n\n```{.r .cell-code}\nsixth_km <- vapply(nbdists(knn6_nb, coords, longlat = TRUE), max, numeric(1))\nsummary(sixth_km)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  53.73   66.07   70.39   75.31   83.39  124.88 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(1, 2), mar = c(1, 1, 3, 1))\nplot_network(distance62_nb, \"Fixed distance: 62 km\")\nplot_network(knn6_nb, \"Adaptive distance: k = 6\", \"#D55E00\")\npar(mfrow = c(1, 1))\n```\n\n::: {.cell-output-display}\n![Fixed 62 km and adaptive six-neighbour networks. Lines in the kNN panel show selected connections, not arrow directions.](Hands-on_Ex0401_files/figure-html/fig-distance-networks-1.png){#fig-distance-networks width=1152}\n:::\n:::\n\n\n# 5 From neighbours to weights\n\nA neighbour list specifies which entries can be nonzero. A weighting rule determines their values. For binary adjacency, `style = \"B\"` gives a weight of one per neighbour; `style = \"W\"` divides each row by its sum. With supplied inverse-distance values, `style = \"B\"` preserves those values: it does **not** row-standardise them. The code therefore stores unstandardised and row-standardised IDW separately. [Weight-coding documentation](https://r-spatial.github.io/spdep/reference/nb2listw.html).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqueen_distances <- nbdists(queen_nb, coords, longlat = TRUE)\nstopifnot(all(unlist(queen_distances) > 0))\ninverse_distance <- lapply(queen_distances, function(d) 1 / d)\nqueen_w <- nb2listw(queen_nb, style = \"W\", zero.policy = FALSE)\nqueen_b <- nb2listw(queen_nb, style = \"B\", zero.policy = FALSE)\nidw_raw <- nb2listw(queen_nb, glist = inverse_distance,\n                    style = \"B\", zero.policy = FALSE)\nidw_w <- nb2listw(queen_nb, glist = inverse_distance,\n                  style = \"W\", zero.policy = FALSE)\nrow_summary <- function(weights, label) {\n  totals <- vapply(weights$weights, sum, numeric(1))\n  data.frame(Weights = label, Minimum_row_sum = min(totals),\n             Maximum_row_sum = max(totals))\n}\nbind_rows(row_summary(queen_b, \"Binary queen\"),\n          row_summary(queen_w, \"Row-standardised queen\"),\n          row_summary(idw_raw, \"Unstandardised IDW (1/km)\"),\n          row_summary(idw_w, \"Row-standardised IDW\")) |> kable(digits = 4)\n```\n\n::: {.cell-output-display}\n\n\n|Weights                   | Minimum_row_sum| Maximum_row_sum|\n|:-------------------------|---------------:|---------------:|\n|Binary queen              |          1.0000|         11.0000|\n|Row-standardised queen    |          1.0000|          1.0000|\n|Unstandardised IDW (1/km) |          0.0209|          0.1714|\n|Row-standardised IDW      |          1.0000|          1.0000|\n\n\n:::\n\n```{.r .cell-code}\nstopifnot(all(abs(vapply(queen_w$weights, sum, numeric(1)) - 1) < 1e-12),\n          all(abs(vapply(idw_w$weights, sum, numeric(1)) - 1) < 1e-12))\ndata.frame(Neighbour = hunan$County[anxiang_neighbours],\n           Distance_km = queen_distances[[anxiang]],\n           Queen_W = queen_w$weights[[anxiang]],\n           IDW_raw = idw_raw$weights[[anxiang]],\n           IDW_W = idw_w$weights[[anxiang]]) |> kable(digits = 4)\n```\n\n::: {.cell-output-display}\n\n\n|Neighbour | Distance_km| Queen_W| IDW_raw|  IDW_W|\n|:---------|-----------:|-------:|-------:|------:|\n|Hanshou   |     65.1219|     0.2|  0.0154| 0.1368|\n|Jinshi    |     25.5337|     0.2|  0.0392| 0.3489|\n|Li        |     54.9058|     0.2|  0.0182| 0.1622|\n|Nan       |     35.6070|     0.2|  0.0281| 0.2502|\n|Taoyuan   |     87.3641|     0.2|  0.0114| 0.1020|\n\n\n:::\n:::\n\n\nNo queen isolates were found. `zero.policy = FALSE` deliberately stops the calculation if that changes; replacing a missing neighbourhood average with zero would require a separate justification.\n\n# 6 Applying the spatial weights\n\nThe spatial lag multiplies the weight matrix by the aligned indicator vector. Equal row-standardised weights yield a neighbour average; binary weights yield a sum. Neither calculation is a test of spatial autocorrelation. [Spatial-lag documentation](https://r-spatial.github.io/spdep/reference/lag.listw.html).\n\n## Neighbour mean and sum\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan$neighbour_mean <- lag.listw(queen_w, hunan$GDPPC)\nhunan$neighbour_sum <- lag.listw(queen_b, hunan$GDPPC)\nhunan$idw_mean <- lag.listw(idw_w, hunan$GDPPC)\nstopifnot(isTRUE(all.equal(hunan$neighbour_mean,\n                          hunan$neighbour_sum / card(queen_nb))))\ndata.frame(Calculation = c(\"Direct mean\", \"Spatial lag\", \"Direct sum\", \"Spatial sum\"),\n           Value = c(mean(hunan$GDPPC[anxiang_neighbours]),\n                     hunan$neighbour_mean[anxiang],\n                     sum(hunan$GDPPC[anxiang_neighbours]),\n                     hunan$neighbour_sum[anxiang])) |> kable(digits = 2)\n```\n\n::: {.cell-output-display}\n\n\n|Calculation |    Value|\n|:-----------|--------:|\n|Direct mean |  24847.2|\n|Spatial lag |  24847.2|\n|Direct sum  | 124236.0|\n|Spatial sum | 124236.0|\n\n\n:::\n:::\n\n\n## Window mean and sum, including the focal county\n\n`include.self()` adds the focal county before weights are constructed. Consequently, a window with five neighbours averages six values rather than five. [Self-inclusion documentation](https://r-spatial.github.io/spdep/reference/include.self.html).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwindow_nb <- include.self(queen_nb)\nwindow_w <- nb2listw(window_nb, style = \"W\", zero.policy = FALSE)\nwindow_b <- nb2listw(window_nb, style = \"B\", zero.policy = FALSE)\nhunan$window_mean <- lag.listw(window_w, hunan$GDPPC)\nhunan$window_sum <- lag.listw(window_b, hunan$GDPPC)\nstopifnot(isTRUE(all.equal(hunan$window_sum, hunan$neighbour_sum + hunan$GDPPC)),\n          isTRUE(all.equal(hunan$window_mean,\n                           hunan$window_sum / (card(queen_nb) + 1))))\nhunan |> st_drop_geometry() |>\n  select(County, GDPPC, neighbour_mean, neighbour_sum, window_mean, window_sum) |>\n  head(10) |> kable(digits = 2)\n```\n\n::: {.cell-output-display}\n\n\n|County    | GDPPC| neighbour_mean| neighbour_sum| window_mean| window_sum|\n|:---------|-----:|--------------:|-------------:|-----------:|----------:|\n|Anxiang   | 23667|       24847.20|        124236|    24650.50|     147903|\n|Hanshou   | 20981|       22724.80|        113624|    22434.17|     134605|\n|Jinshi    | 34592|       24143.25|         96573|    26233.00|     131165|\n|Li        | 24473|       27737.50|        110950|    27084.60|     135423|\n|Linli     | 25554|       27270.25|        109081|    26927.00|     134635|\n|Shimen    | 27137|       21248.80|        106244|    22230.17|     133381|\n|Liuyang   | 63118|       43747.00|        174988|    47621.20|     238106|\n|Ningxiang | 62202|       33582.71|        235079|    37160.12|     297281|\n|Wangcheng | 70666|       45651.17|        273907|    49224.71|     344573|\n|Anren     | 12761|       32027.62|        256221|    29886.89|     268982|\n\n\n:::\n:::\n\n\n## Mapping comparable quantities\n\nThe original indicator and three averages share one set of breaks. The two sums use their own shared scale. Summing county GDP-per-capita ratios does **not** give combined GDP or population-weighted GDP per capita; those require appropriate GDP and population denominators. These sums illustrate the operator, not a regional economic total.\n\n\n::: {.cell}\n\n```{.r .cell-code}\naverage_fields <- c(\"GDPPC\", \"neighbour_mean\", \"window_mean\", \"idw_mean\")\naverage_breaks <- pretty(range(unlist(st_drop_geometry(hunan)[average_fields])), n = 5)\nmap_value <- function(field, title, breaks, legend_title) {\n  tm_shape(hunan) +\n    tm_polygons(fill = field,\n                fill.scale = tm_scale_intervals(breaks = breaks,\n                                                 values = \"brewer.yl_or_br\"),\n                fill.legend = tm_legend(title = legend_title),\n                col = \"white\", lwd = 0.4) +\n    tm_title(title, size = 0.9) +\n    tm_layout(frame = FALSE, legend.outside = TRUE)\n}\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_arrange(\n  map_value(\"GDPPC\", \"Original GDPPC\", average_breaks, \"GDPPC scale\"),\n  map_value(\"neighbour_mean\", \"Queen neighbour mean\", average_breaks, \"GDPPC scale\"),\n  map_value(\"window_mean\", \"Window mean (including self)\", average_breaks, \"GDPPC scale\"),\n  map_value(\"idw_mean\", \"Inverse-distance neighbour mean\", average_breaks, \"GDPPC scale\"),\n  ncol = 2)\n```\n\n::: {.cell-output-display}\n![The original indicator and three spatial averages, using common class breaks.](Hands-on_Ex0401_files/figure-html/fig-spatial-averages-1.png){#fig-spatial-averages width=1152}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum_breaks <- pretty(range(c(hunan$neighbour_sum, hunan$window_sum)), n = 5)\ntmap_arrange(\n  map_value(\"neighbour_sum\", \"Neighbour sum\", sum_breaks, \"Sum of GDPPC values\"),\n  map_value(\"window_sum\", \"Window sum (including self)\", sum_breaks, \"Sum of GDPPC values\"),\n  ncol = 2)\n```\n\n::: {.cell-output-display}\n![Sums of county GDPPC values. These are demonstrations of weighted sums, not estimates of combined GDP.](Hands-on_Ex0401_files/figure-html/fig-spatial-sums-1.png){#fig-spatial-sums width=1152}\n:::\n:::\n\n\n# 7 Validation and reproducibility\n\nThe final checks verify the computations for every county, not just the displayed example. They also confirm that none of the downloaded files changed during rendering.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndirect_means <- vapply(queen_nb, function(j) mean(hunan$GDPPC[j]), numeric(1))\ndirect_sums <- vapply(queen_nb, function(j) sum(hunan$GDPPC[j]), numeric(1))\nchecks <- data.frame(\n  Check = c(\"One-to-one join retains all 88 counties\",\n            \"Queen lag equals direct neighbour mean\",\n            \"Binary lag equals direct neighbour sum\",\n            \"Window sum includes exactly the focal value\",\n            \"Downloaded inputs remain unchanged\"),\n  Passed = c(nrow(hunan) == 88L,\n             max(abs(direct_means - hunan$neighbour_mean)) < 1e-8,\n             max(abs(direct_sums - hunan$neighbour_sum)) < 1e-8,\n             max(abs(hunan$window_sum - hunan$neighbour_sum - hunan$GDPPC)) < 1e-8,\n             identical(raw_md5, tools::md5sum(raw_files))))\nstopifnot(all(checks$Passed))\nkable(checks)\n```\n\n::: {.cell-output-display}\n\n\n|Check                                       |Passed |\n|:-------------------------------------------|:------|\n|One-to-one join retains all 88 counties     |TRUE   |\n|Queen lag equals direct neighbour mean      |TRUE   |\n|Binary lag equals direct neighbour sum      |TRUE   |\n|Window sum includes exactly the focal value |TRUE   |\n|Downloaded inputs remain unchanged          |TRUE   |\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.5.3 (2026-03-11 ucrt)\nPlatform: x86_64-w64-mingw32/x64\nRunning under: Windows 11 x64 (build 26200)\n\nMatrix products: default\n  LAPACK version 3.12.1\n\nlocale:\n[1] LC_COLLATE=English_United States.utf8 \n[2] LC_CTYPE=English_United States.utf8   \n[3] LC_MONETARY=English_United States.utf8\n[4] LC_NUMERIC=C                          \n[5] LC_TIME=English_United States.utf8    \n\ntime zone: Asia/Singapore\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n[1] knitr_1.51   readr_2.2.0  dplyr_1.2.1  tmap_4.4     spdep_1.4-2 \n[6] spData_2.3.5 sf_1.1-0    \n\nloaded via a namespace (and not attached):\n [1] xfun_0.57            raster_3.6-32        htmlwidgets_1.6.4   \n [4] lattice_0.22-9       tzdb_0.5.0           vctrs_0.7.3         \n [7] tools_4.5.3          crosstalk_1.2.2      generics_0.1.4      \n[10] parallel_4.5.3       tibble_3.3.1         proxy_0.4-29        \n[13] pkgconfig_2.0.3      KernSmooth_2.23-26   data.table_1.18.2.1 \n[16] leaflet_2.2.3        lifecycle_1.0.5      compiler_4.5.3      \n[19] deldir_2.0-4         microbenchmark_1.5.0 terra_1.9-27        \n[22] codetools_0.2-20     leafsync_0.1.0       leaflegend_1.2.8    \n[25] stars_0.7-2          htmltools_0.5.9      class_7.3-23        \n[28] yaml_2.3.12          crayon_1.5.3         pillar_1.11.1       \n[31] classInt_0.4-11      lwgeom_0.2-16        wk_0.9.5            \n[34] boot_1.3-32          abind_1.4-8          tidyselect_1.2.1    \n[37] digest_0.6.39        fastmap_1.2.0        grid_4.5.3          \n[40] colorspace_2.1-2     cli_3.6.6            logger_0.4.2        \n[43] magrittr_2.0.5       maptiles_0.11.0      base64enc_0.1-6     \n[46] XML_3.99-0.23        cols4all_0.10        leafem_0.2.5        \n[49] e1071_1.7-17         withr_3.0.2          bit64_4.8.0         \n[52] sp_2.2-1             rmarkdown_2.31       igraph_2.3.1        \n[55] bit_4.6.0            otel_0.2.0           png_0.1-9           \n[58] hms_1.1.4            evaluate_1.0.5       tmaptools_3.3       \n[61] s2_1.1.9             rlang_1.2.0          Rcpp_1.1.1-1.1      \n[64] glue_1.8.1           DBI_1.3.0            vroom_1.7.1         \n[67] jsonlite_2.0.0       R6_2.6.1             spacesXYZ_1.6-0     \n[70] units_1.0-1         \n```\n\n\n:::\n:::\n\n\n# References\n\n- [Chapter 8: Spatial Weights and Applications](https://r4gdsa.netlify.app/chap08.html)\n- [Instructor's pinned Lesson 4 data](https://github.com/tskam/ISSS626-AY2026-27Aug/tree/966eea6df498b38f10bc209d07a922f4d87b95d9/lesson/Lesson04/data)\n- [spdep documentation](https://r-spatial.github.io/spdep/)\n- [sf geometry operations](https://r-spatial.github.io/sf/reference/geos_unary.html)\n- [tmap 4 polygon layers](https://r-tmap.github.io/tmap/reference/tm_polygons.html)\n",
    "supporting": [
      "Hands-on_Ex0401_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}