{
  "hash": "dc80c119e93a83c262608b6376d226e9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Hands-on Exercise 1(1): Geospatial Data Science with R\"\nauthor: \"JUNCHEN LI\"\ndate: \"August 27, 2026\"\ndate-modified: \"last-modified\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: false\n    code-tools: true\neditor: visual\nexecute:\n  eval: true\n  echo: true\n  warning: false\n  message: false\n  freeze: auto\n---\n\n# Overview\n\nThis hands-on exercise introduces the **sf** data model and a simple spatial-analysis workflow in R. I work with polygon, line, and point data, check coordinate reference systems, convert a non-spatial table into an `sf` object, and perform buffer, intersection, and point-in-polygon operations.\n\nThe workflow is adapted from [Chapter 1: Geospatial Data Science with R](https://r4gdsa.netlify.app/chap01.html). The data files used here are stored locally so that the exercise remains reproducible.\n\n## Learning objectives\n\nBy the end of this exercise, I should be able to:\n\n- import GeoJSON and CSV files into R;\n- recognise polygon, line, and point geometries;\n- inspect and transform coordinate reference systems;\n- convert longitude and latitude columns into spatial points; and\n- apply basic geoprocessing operations with **sf**.\n\n# Getting started\n\n## Loading the R packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(\n  sf,\n  tidyverse,\n  rvest,\n  knitr\n)\n```\n:::\n\n\n## Data used\n\n| File | Geometry / type | Purpose |\n|---|---|---|\n| `MP14_SUBZONE_WEB_PL.shp` | Multipolygon | Master Plan 2014 subzone boundaries |\n| `CyclingPathGazette.shp` | Multilinestring | Cycling path network |\n| `PreSchoolsLocation.kml` | Point | Preschool locations |\n| `listings.csv` | Aspatial CSV | Airbnb listings with coordinates |\n\nThe three geospatial datasets were obtained from [data.gov.sg](https://data.gov.sg/), while the listings data came from [Inside Airbnb](https://insideairbnb.com/get-the-data/). The current cycling-path and preschool downloads were converted to the shapefile and KML formats used in the chapter.\n\n# Importing geospatial data\n\n## Subzone boundaries\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz <- st_read(\n  dsn = \"data/geospatial\",\n  layer = \"MP14_SUBZONE_WEB_PL\",\n  quiet = TRUE\n) |>\n  st_make_valid()\n\nmpsz\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 323 features and 15 fields\nGeometry type: GEOMETRY\nDimension:     XY\nBounding box:  xmin: 2667.538 ymin: 15748.72 xmax: 56396.44 ymax: 50256.33\nProjected CRS: SVY21\nFirst 10 features:\n   OBJECTID SUBZONE_NO       SUBZONE_N SUBZONE_C CA_IND      PLN_AREA_N\n1         1          1    MARINA SOUTH    MSSZ01      Y    MARINA SOUTH\n2         2          1    PEARL'S HILL    OTSZ01      Y          OUTRAM\n3         3          3       BOAT QUAY    SRSZ03      Y SINGAPORE RIVER\n4         4          8  HENDERSON HILL    BMSZ08      N     BUKIT MERAH\n5         5          3         REDHILL    BMSZ03      N     BUKIT MERAH\n6         6          7  ALEXANDRA HILL    BMSZ07      N     BUKIT MERAH\n7         7          9   BUKIT HO SWEE    BMSZ09      N     BUKIT MERAH\n8         8          2     CLARKE QUAY    SRSZ02      Y SINGAPORE RIVER\n9         9         13 PASIR PANJANG 1    QTSZ13      N      QUEENSTOWN\n10       10          7       QUEENSWAY    QTSZ07      N      QUEENSTOWN\n   PLN_AREA_C       REGION_N REGION_C          INC_CRC FMEL_UPD_D   X_ADDR\n1          MS CENTRAL REGION       CR 5ED7EB253F99252E 2014-12-05 31595.84\n2          OT CENTRAL REGION       CR 8C7149B9EB32EEFC 2014-12-05 28679.06\n3          SR CENTRAL REGION       CR C35FEFF02B13E0E5 2014-12-05 29654.96\n4          BM CENTRAL REGION       CR 3775D82C5DDBEFBD 2014-12-05 26782.83\n5          BM CENTRAL REGION       CR 85D9ABEF0A40678F 2014-12-05 26201.96\n6          BM CENTRAL REGION       CR 9D286521EF5E3B59 2014-12-05 25358.82\n7          BM CENTRAL REGION       CR 7839A8577144EFE2 2014-12-05 27680.06\n8          SR CENTRAL REGION       CR 48661DC0FBA09F7A 2014-12-05 29253.21\n9          QT CENTRAL REGION       CR 1F721290C421BFAB 2014-12-05 22077.34\n10         QT CENTRAL REGION       CR 3580D2AFFBEE914C 2014-12-05 24168.31\n     Y_ADDR SHAPE_Leng SHAPE_Area                       geometry\n1  29220.19   5267.381  1630379.3 POLYGON ((31495.56 30140.01...\n2  29782.05   3506.107   559816.2 POLYGON ((29092.28 30021.89...\n3  29974.66   1740.926   160807.5 POLYGON ((29932.33 29879.12...\n4  29933.77   3313.625   595428.9 POLYGON ((27131.28 30059.73...\n5  30005.70   2825.594   387429.4 POLYGON ((26451.03 30396.46...\n6  29991.38   4428.913  1030378.8 POLYGON ((25899.7 29766.74,...\n7  30230.86   3275.312   551732.0 POLYGON ((27746.95 30497.17...\n8  30222.86   2208.619   290184.7 POLYGON ((29351.26 29902.05...\n9  29893.78   6571.323  1084792.3 POLYGON ((20996.49 30542.35...\n10 30104.18   3454.239   631644.3 POLYGON ((24472.11 29621.83...\n```\n\n\n:::\n:::\n\n\nThe object contains one feature for each Master Plan 2014 subzone. Its attributes include the subzone, planning-area, and region names.\n\n## Cycling paths\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncycling_path <- st_read(\n  dsn = \"data/geospatial\",\n  layer = \"CyclingPathGazette\",\n  quiet = TRUE\n)\n\ncycling_path\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 8523 features and 6 fields\nGeometry type: MULTILINESTRING\nDimension:     XY\nBounding box:  xmin: 6156.422 ymin: 27550.13 xmax: 42809.37 ymax: 49878.85\nProjected CRS: SVY21 / Singapore TM\nFirst 10 features:\n   OBJECTI         CYL_PAT                  AGENCY_          INC_CRC\n1   147638        Sengkang Land Transport Authority 51EE5DB1B7BA2BB5\n2   147639   Bukit Panjang Land Transport Authority 8905286E2129158F\n3   147640      Ang Mo Kio Land Transport Authority C1BE0614AAF208D7\n4   147641 Tuas & Joo Koon Land Transport Authority 5F962E258536A011\n5   147642 Tuas & Joo Koon Land Transport Authority 00DD4B045A574193\n6   147643         Punggol Land Transport Authority 08C2F9FD74BCAE1A\n7   147644     Bukit Batok Land Transport Authority C0A69F96672D5D34\n8   147645         Hougang Land Transport Authority CFA9CA5FD65F043E\n9   147646     Bukit Batok             LTA (Others) F0EEBE7ACD5DA9CB\n10  147647     Bukit Batok Land Transport Authority CBECD7A5AF8ED813\n          FMEL_UP    SHAPE_1                       geometry\n1  20260605154757  39.178917 MULTILINESTRING ((35373.74 ...\n2  20240714130101  51.395448 MULTILINESTRING ((20175.72 ...\n3  20240714130101   5.799726 MULTILINESTRING ((30077.72 ...\n4  20260605154757 124.071825 MULTILINESTRING ((6164.266 ...\n5  20260605154757   7.579566 MULTILINESTRING ((6163.715 ...\n6  20260605154757 408.708367 MULTILINESTRING ((36704.16 ...\n7  20260605154757  52.261327 MULTILINESTRING ((18586.21 ...\n8  20260605154756  30.194897 MULTILINESTRING ((35072.95 ...\n9  20260605154757   6.626497 MULTILINESTRING ((18585.95 ...\n10 20260605154757  43.660005 MULTILINESTRING ((18429.55 ...\n```\n\n\n:::\n:::\n\n\n## Preschool locations\n\nThe preschool GeoJSON stores useful attributes inside an HTML description. The helper function below extracts a requested value from that table.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nextract_description_value <- function(description, field_name) {\n  attributes <- description |>\n    read_html() |>\n    html_table(fill = TRUE) |>\n    pluck(1)\n\n  names(attributes)[1:2] <- c(\"field\", \"value\")\n\n  result <- attributes |>\n    filter(field == field_name) |>\n    pull(value)\n\n  if (length(result) == 0) NA_character_ else result[[1]]\n}\n\npreschool <- st_read(\n  \"data/geospatial/PreSchoolsLocation.kml\",\n  quiet = TRUE\n) |>\n  mutate(\n    CENTRE_NAME = map_chr(\n      Description,\n      ~ extract_description_value(.x, \"CENTRE_NAME\")\n    )\n  )\n\npreschool |>\n  st_drop_geometry() |>\n  select(CENTRE_NAME) |>\n  head() |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|CENTRE_NAME                                  |\n|:--------------------------------------------|\n|CHILDREN'S COVE PRESCHOOL PTE.LTD.           |\n|CHILDREN'S COVE PTE. LTD.                    |\n|CHILDREN'S VINEYARD PRESCHOOL PTE. LTD       |\n|CHILDTIME CARE & DEVELOPMENT CENTRE PTE.LTD. |\n|CHILTERN HOUSE                               |\n|CHILTERN HOUSE EAST COAST                    |\n\n\n:::\n:::\n\n\n# Examining spatial objects\n\n## Geometry types and coordinate reference systems\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspatial_summary <- tibble(\n  data = c(\"Subzones\", \"Cycling paths\", \"Preschools\"),\n  features = c(nrow(mpsz), nrow(cycling_path), nrow(preschool)),\n  geometry = c(\n    as.character(st_geometry_type(mpsz, by_geometry = FALSE)),\n    as.character(st_geometry_type(cycling_path, by_geometry = FALSE)),\n    as.character(st_geometry_type(preschool, by_geometry = FALSE))\n  ),\n  epsg = c(\n    st_crs(mpsz)$epsg,\n    st_crs(cycling_path)$epsg,\n    st_crs(preschool)$epsg\n  )\n)\n\nspatial_summary |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|data          | features|geometry        | epsg|\n|:-------------|--------:|:---------------|----:|\n|Subzones      |      323|GEOMETRY        |   NA|\n|Cycling paths |     8523|MULTILINESTRING | 3414|\n|Preschools    |     2290|POINT           | 4326|\n\n\n:::\n:::\n\n\nAll three files use WGS 84 (`EPSG:4326`). This geographic CRS is useful for sharing data, but distance and area calculations should use a projected CRS. I therefore transform the layers to Singapore SVY21 (`EPSG:3414`).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz_svy21 <- st_transform(mpsz, 3414)\ncycling_path_svy21 <- st_transform(cycling_path, 3414)\npreschool_svy21 <- st_transform(preschool, 3414)\n\nst_crs(mpsz_svy21)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: EPSG:3414 \n  wkt:\nPROJCRS[\"SVY21 / Singapore TM\",\n    BASEGEOGCRS[\"SVY21\",\n        DATUM[\"SVY21\",\n            ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n                LENGTHUNIT[\"metre\",1]]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4757]],\n    CONVERSION[\"Singapore Transverse Mercator\",\n        METHOD[\"Transverse Mercator\",\n            ID[\"EPSG\",9807]],\n        PARAMETER[\"Latitude of natural origin\",1.36666666666667,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8801]],\n        PARAMETER[\"Longitude of natural origin\",103.833333333333,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8802]],\n        PARAMETER[\"Scale factor at natural origin\",1,\n            SCALEUNIT[\"unity\",1],\n            ID[\"EPSG\",8805]],\n        PARAMETER[\"False easting\",28001.642,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8806]],\n        PARAMETER[\"False northing\",38744.572,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8807]]],\n    CS[Cartesian,2],\n        AXIS[\"northing (N)\",north,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1]],\n        AXIS[\"easting (E)\",east,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1]],\n    USAGE[\n        SCOPE[\"Cadastre, engineering survey, topographic mapping.\"],\n        AREA[\"Singapore - onshore and offshore.\"],\n        BBOX[1.13,103.59,1.47,104.07]],\n    ID[\"EPSG\",3414]]\n```\n\n\n:::\n:::\n\n\n## Plotting different geometry layers\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(\n  st_geometry(mpsz_svy21),\n  col = \"grey96\",\n  border = \"grey65\",\n  main = \"Subzones, cycling paths, and preschools\"\n)\nplot(\n  st_geometry(cycling_path_svy21),\n  col = \"#2C7FB8\",\n  lwd = 0.6,\n  add = TRUE\n)\nplot(\n  st_geometry(preschool_svy21),\n  col = \"#D95F0E\",\n  pch = 20,\n  cex = 0.25,\n  add = TRUE\n)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex0101_files/figure-html/unnamed-chunk-7-1.png){width=960}\n:::\n:::\n\n\n# Converting aspatial data into an sf object\n\nThe Airbnb table contains longitude and latitude values. `st_as_sf()` converts these columns into point geometry.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlistings <- read_csv(\n  \"data/aspatial/listings.csv\",\n  show_col_types = FALSE\n)\n\nairbnb_sf <- listings |>\n  filter(!is.na(longitude), !is.na(latitude)) |>\n  st_as_sf(\n    coords = c(\"longitude\", \"latitude\"),\n    crs = 4326,\n    remove = FALSE\n  ) |>\n  st_transform(3414)\n\nairbnb_sf |>\n  select(name, room_type, price) |>\n  head()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 6 features and 3 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 28503.19 ymin: 32635.68 xmax: 42209.55 ymax: 36810.25\nProjected CRS: SVY21 / Singapore TM\n# A tibble: 6 x 4\n  name                                room_type  price            geometry\n  <chr>                               <chr>      <dbl>         <POINT [m]>\n1 Ensuite Room (Room 1 & 2) near EXPO Private r~    NA  (41972.5 36390.05)\n2 B&B  Room 1 near Airport & EXPO     Private r~    NA (42051.51 36630.01)\n3 Room 2-near Airport & EXPO          Private r~    NA (42209.55 36383.43)\n4 5 mins walk from Newton subway      Private r~    32    (28659 32635.68)\n5 Budget short stay room near  EXPO   Private r~    15  (42198.4 36810.25)\n6 5mins from Newton Train Station     Private r~    NA (28503.19 32637.89)\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(\n  st_geometry(mpsz_svy21),\n  col = \"grey97\",\n  border = \"grey75\",\n  main = \"Airbnb listings in Singapore\"\n)\nplot(\n  st_geometry(airbnb_sf),\n  col = adjustcolor(\"#7B3294\", alpha.f = 0.45),\n  pch = 20,\n  cex = 0.45,\n  add = TRUE\n)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex0101_files/figure-html/unnamed-chunk-9-1.png){width=864}\n:::\n:::\n\n\n# Basic geoprocessing\n\n## Five-metre cycling-path buffer in Tampines West\n\nI first select the Tampines West subzone, retain the cycling paths that intersect it, and then build a five-metre buffer. Because SVY21 uses metres, the buffer distance has a clear physical meaning.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntampines_west <- mpsz_svy21 |>\n  filter(SUBZONE_N == \"TAMPINES WEST\")\n\ntampines_cycling <- cycling_path_svy21 |>\n  st_filter(tampines_west)\n\ncycling_buffer_5m <- tampines_cycling |>\n  st_buffer(dist = 5) |>\n  st_intersection(tampines_west)\n\nbuffer_area_km2 <- cycling_buffer_5m |>\n  summarise() |>\n  st_area() |>\n  as.numeric() / 1e6\n\ntibble(\n  cycling_features = nrow(tampines_cycling),\n  buffered_area_km2 = round(buffer_area_km2, 3)\n) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n| cycling_features| buffered_area_km2|\n|----------------:|-----------------:|\n|              169|             0.106|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(\n  st_geometry(tampines_west),\n  col = \"grey95\",\n  border = \"grey40\",\n  main = \"Five-metre buffer around cycling paths in Tampines West\"\n)\nplot(\n  st_geometry(cycling_buffer_5m),\n  col = adjustcolor(\"#41B6C4\", alpha.f = 0.65),\n  border = NA,\n  add = TRUE\n)\nplot(\n  st_geometry(tampines_cycling),\n  col = \"#253494\",\n  lwd = 1,\n  add = TRUE\n)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex0101_files/figure-html/unnamed-chunk-11-1.png){width=768}\n:::\n:::\n\n\n## Counting preschools within each subzone\n\n`st_intersects()` returns the matching preschool points for each polygon. The length of each result is the number of preschools in that subzone.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz_analysis <- mpsz_svy21 |>\n  mutate(\n    PRE_SCH_COUNT = lengths(st_intersects(geometry, preschool_svy21)),\n    AREA_KM2 = as.numeric(st_area(geometry)) / 1e6,\n    PRE_SCH_DENSITY = PRE_SCH_COUNT / AREA_KM2\n  )\n\nmpsz_analysis |>\n  st_drop_geometry() |>\n  select(SUBZONE_N, PLN_AREA_N, PRE_SCH_COUNT, AREA_KM2, PRE_SCH_DENSITY) |>\n  slice_max(PRE_SCH_COUNT, n = 10, with_ties = FALSE) |>\n  mutate(\n    AREA_KM2 = round(AREA_KM2, 2),\n    PRE_SCH_DENSITY = round(PRE_SCH_DENSITY, 2)\n  ) |>\n  kable(\n    caption = \"Ten subzones with the largest number of preschools\"\n  )\n```\n\n::: {.cell-output-display}\n\n\nTable: Ten subzones with the largest number of preschools\n\n|SUBZONE_N            |PLN_AREA_N  | PRE_SCH_COUNT| AREA_KM2| PRE_SCH_DENSITY|\n|:--------------------|:-----------|-------------:|--------:|---------------:|\n|TAMPINES EAST        |TAMPINES    |            72|     4.34|           16.59|\n|WOODLANDS EAST       |WOODLANDS   |            54|     2.55|           21.15|\n|ALJUNIED             |GEYLANG     |            40|     2.96|           13.52|\n|TAMPINES WEST        |TAMPINES    |            38|     3.48|           10.93|\n|BEDOK NORTH          |BEDOK       |            38|     3.20|           11.86|\n|FRANKEL              |BEDOK       |            36|     4.30|            8.38|\n|SENGKANG TOWN CENTRE |SENGKANG    |            33|     1.46|           22.67|\n|YUNNAN               |JURONG WEST |            32|     2.21|           14.50|\n|HONG KAH             |JURONG WEST |            30|     1.79|           16.73|\n|BEDOK SOUTH          |BEDOK       |            29|     3.00|            9.68|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(\n  mpsz_analysis[\"PRE_SCH_COUNT\"],\n  pal = function(n) hcl.colors(n, \"YlOrRd\", rev = TRUE),\n  main = \"Number of preschools by subzone\",\n  key.pos = 1\n)\n```\n\n::: {.cell-output-display}\n![](Hands-on_Ex0101_files/figure-html/unnamed-chunk-13-1.png){width=864}\n:::\n:::\n\n\n# Reflection\n\nThis exercise shows why the CRS is an analytical decision rather than only a data label. WGS 84 is suitable for storing geographic coordinates, whereas SVY21 is more appropriate for Singapore-based distance and area calculations. The same `sf` structure also allows polygon, line, and point layers to be combined with a consistent set of R verbs.\n\n# References\n\n- [Geospatial Data Science with R, Chapter 1](https://r4gdsa.netlify.app/chap01.html)\n- [data.gov.sg](https://data.gov.sg/)\n- [Inside Airbnb data portal](https://insideairbnb.com/get-the-data/)\n",
    "supporting": [
      "Hands-on_Ex0101_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}