---
title: "In_class_ex04"
author: "JUNCHEN LI"
date: "September 19, 2026"
date-modified: today
format:
  html:
    toc: true
    toc-depth: 3
    code-fold: false
    code-tools: true
editor: visual
execute:
  eval: true
  echo: true
  warning: false
  message: false
  freeze: auto
---

### Package Loading

::: {style="front-size: 1.50em"}
```{r}
pacman::p_load(
  sf,
  tidyverse,
  rvest,
  knitr,
  spdep,
  tmap,
  GWmodel,
  ggstatsplot
)
```
:::

### data Preparing

```{r}
hunan_sf <- st_read(dsn = "data/geospatial", layer = "Hunan")
hunan2012 <- read_csv("data/aspatial/Hunan_2012.csv")

hunan_sf <- left_join(hunan_sf, hunan2012) %>%
  select(1:3, 7,15,16,31,32)
```

### Mapping GDPPC

::: panel-tabset
## DIY

```{r, echo=FALSE}
#| fig-width: 16
#| fig-height: 6
basemap <- tm_shape(hunan_sf) + 
  tm_polygons() +
  tm_text("NAME_3", size=0.5)

gdppc <- qtm(hunan_sf, "GDPPC") +
  tm_layout(
    legend.position = c("left", "bottom"))
tmap_arrange(basemap,gdppc,asp = 1,ncol = 2)
```

## The code

```{r, eval=FALSE}
basemap <- tm_shape(hunan_sf) + 
  tm_polygons() +
  tm_text("NAME_3", size=0.5)

gdppc <- qtm(hunan_sf, "GDPPC") +
  tm_layout(
    legend.position = c("left", "bottom"))
tmap_arrange(basemap,gdppc,asp = 1,ncol = 2)
```
:::

### Converting to SpatialPolygonDataFrame

```{r}
hunan_sp <- hunan_sf %>%
  as_Spatial()
```

### Geographically Weighted Summary Statistics(GSWW) with adaptivev bandwidth

#### Determine adaptive bandwidth

```{r}
bw_CV <- bw.gwr(GDPPC ~1,
                data = hunan_sp,
                approach = "CV",
                adaptive = TRUE,
                kernel = "bisquare",
                longlat = T)
```
