{
  "hash": "fc7c111e028a95576e43a54307dc889a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Hands-on Exercise 5(1): Global Spatial Autocorrelation\"\nauthor: \"JUNCHEN LI\"\ndate: \"September 24, 2026\"\ndate-modified: \"last-modified\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: true\n    code-summary: \"Show code\"\n    code-tools: true\neditor: source\nexecute:\n  echo: true\n  warning: false\n  message: false\n  freeze: auto\n---\n\n# Overview\n\nThis exercise accompanies [Chapter 9](https://r4gdsa.netlify.app/chap09.html). The question is whether neighbouring Hunan counties have similar GDP per capita in 2012. The analysis treats county boundaries as fixed and tests the arrangement of an attribute, rather than the locations of point events. [Part 2](Hands-on_Ex0502.qmd) examines individual counties.\n\n# 1 Data and preparation\n\nBoth parts use `data/geospatial/Hunan.shp` and its companion files, together with `data/aspatial/Hunan_2012.csv`. The data are downloaded from the instructor's [pinned course repository](https://github.com/tskam/ISSS626-AY2026-27Aug/tree/966eea6df498b38f10bc209d07a922f4d87b95d9/lesson/Lesson04/data). `data/download-data.R` retrieves the inputs; `data/download-manifest.txt` records URLs, retrieval date and checksums. **2012 is the indicator year**, not the download year. Values retain the supplied scale.\n\n## Packages\n\nInstall missing packages once in the R console before rendering. The document does not install software during a render.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(sf)\nlibrary(spdep)\nlibrary(tmap)\nlibrary(dplyr)\nlibrary(readr)\nlibrary(ggplot2)\nlibrary(knitr)\ntmap_mode(\"plot\")\ntheme_set(theme_minimal(base_size = 12))\n```\n:::\n\n\n## Import and join\n\nAn explicit county key prevents an accidental join on unrelated columns. The checks require a unique match for every polygon and retain polygon order for the weights.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboundary <- st_read(\"data/geospatial/Hunan.shp\", quiet = TRUE)\nattributes <- read_csv(\"data/aspatial/Hunan_2012.csv\", show_col_types = FALSE)\nstopifnot(nrow(boundary) == 88L, nrow(attributes) == 88L,\n          !anyDuplicated(boundary$County), !anyDuplicated(attributes$County),\n          setequal(boundary$County, attributes$County),\n          all(st_is_valid(boundary)), !any(st_is_empty(boundary)))\nhunan <- left_join(boundary, select(attributes, County, GDPPC),\n                   by = \"County\", relationship = \"one-to-one\")\nstopifnot(identical(hunan$County, boundary$County),\n          all(is.finite(hunan$GDPPC)), all(hunan$GDPPC > 0))\ndata.frame(Counties = nrow(hunan), Missing_GDPPC = sum(is.na(hunan$GDPPC)),\n           Minimum = min(hunan$GDPPC), Median = median(hunan$GDPPC),\n           Maximum = max(hunan$GDPPC)) |> kable()\n```\n\n::: {.cell-output-display}\n\n\n| Counties| Missing_GDPPC| Minimum| Median| Maximum|\n|--------:|-------------:|-------:|------:|-------:|\n|       88|             0|    8497|  20433|   88656|\n\n\n:::\n:::\n\n\n# 2 Two views of the same attribute\n\n\n::: {.cell}\n\n```{.r .cell-code}\nindicator_map <- function(style, title) {\n  tm_shape(hunan) +\n    tm_polygons(fill = \"GDPPC\",\n      fill.scale = tm_scale_intervals(style = style, n = 5,\n                                      values = \"brewer.blues\"),\n      fill.legend = tm_legend(title = \"GDPPC (2012)\"),\n      col = \"white\", lwd = 0.4) +\n    tm_title(title, size = 1) +\n    tm_layout(frame = FALSE, legend.outside = TRUE)\n}\ntmap_arrange(indicator_map(\"equal\", \"Equal intervals\"),\n             indicator_map(\"quantile\", \"Quantiles\"), ncol = 2)\n```\n\n::: {.cell-output-display}\n![Equal-interval and quantile classifications of Hunan GDPPC, 2012.](Hands-on_Ex0501_files/figure-html/fig-classification-1.png){#fig-classification width=1152}\n:::\n:::\n\n\nEqual intervals preserve equal numerical widths, while quantiles distribute counties more evenly among classes. A colour cluster depends partly on these choices. Neither map alone supplies a statistical test, and GDP per capita should not be interpreted as every resident's income.\n\n# 3 Queen neighbours and spatial weights\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqueen <- poly2nb(hunan, queen = TRUE, row.names = hunan$County)\nweights <- nb2listw(queen, style = \"W\", zero.policy = FALSE)\nstopifnot(all(card(queen) > 0),\n          max(abs(vapply(weights$weights, sum, numeric(1)) - 1)) < 1e-12)\ndata.frame(Counties = length(queen), Directed_links = sum(card(queen)),\n           Minimum_neighbours = min(card(queen)),\n           Maximum_neighbours = max(card(queen)),\n           Mean_neighbours = mean(card(queen))) |> kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n| Counties| Directed_links| Minimum_neighbours| Maximum_neighbours| Mean_neighbours|\n|--------:|--------------:|------------------:|------------------:|---------------:|\n|       88|            448|                  1|                 11|           5.091|\n\n\n:::\n:::\n\n\nThere are **448 directed links**. A shared boundary point is sufficient for queen adjacency. Row standardisation gives each county a weighted neighbour average; it does not correct for omitted counties outside the province. Changing the neighbour definition changes the question being tested.\n\n# 4 Global Moran's I\n\n## Analytical test\n\nThe null randomly assigns the observed GDPPC values to the fixed counties. The one-sided alternative tests positive spatial association. Exchangeability is an assumption, not proof that economic development is generated randomly.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmoran_result <- moran.test(hunan$GDPPC, weights,\n                           alternative = \"greater\", randomisation = TRUE)\nmoran_result\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  hunan$GDPPC  \nweights: weights    \n\nMoran I statistic standard deviate = 4.7351, p-value = 1.095e-06\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n      0.300749970      -0.011494253       0.004348351 \n```\n\n\n:::\n:::\n\n\nThe observed I is **0.3007**, compared with the randomisation expectation **-0.0115**. The analytical p-value is **1.09e-06**. A positive value indicates a province-wide tendency for similar values to be adjacent; it does not locate individual clusters or identify a cause.\n\n## Monte Carlo test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nmoran_sim <- moran.mc(hunan$GDPPC, weights, nsim = 999,\n                      alternative = \"greater\")\nmoran_sim\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  hunan$GDPPC \nweights: weights  \nnumber of simulations + 1: 1000 \n\nstatistic = 0.30075, observed rank = 1000, p-value = 0.001\nalternative hypothesis: greater\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data.frame(I = moran_sim$res[seq_len(999)]), aes(I)) +\n  geom_histogram(bins = 25, fill = \"#4878a8\", colour = \"white\") +\n  geom_vline(xintercept = unname(moran_sim$statistic), colour = \"#b2182b\", linewidth = 1) +\n  geom_vline(xintercept = -1/87, linetype = \"dashed\") +\n  labs(x = \"Moran's I under random reassignment\", y = \"Permutations\")\n```\n\n::: {.cell-output-display}\n![Permutation distribution of Moran's I; the red line marks the observed statistic.](Hands-on_Ex0501_files/figure-html/fig-moran-null-1.png){#fig-moran-null width=672}\n:::\n:::\n\n\nThe simulated reference contains only the 999 reassigned datasets; the observed value is excluded from the histogram. The permutation p-value is **0.001**. With 999 permutations, tail probabilities have limited resolution. This test and the analytical test use the same data and weights, so agreement is not independent replication.\n\n## Moran scatterplot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nz <- as.numeric(scale(hunan$GDPPC))\nwz <- lag.listw(weights, z)\nslope <- unname(coef(lm(wz ~ 0 + z))[1])\nstopifnot(abs(slope - unname(moran_result$estimate[1])) < 1e-10)\nggplot(data.frame(z, wz), aes(z, wz)) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", colour = \"grey60\") +\n  geom_vline(xintercept = 0, linetype = \"dashed\", colour = \"grey60\") +\n  geom_point(colour = \"#2166ac\", size = 2) +\n  geom_abline(intercept = 0, slope = slope, colour = \"#b2182b\") +\n  labs(x = \"Standardised GDPPC\", y = \"Spatial lag of standardised GDPPC\")\n```\n\n::: {.cell-output-display}\n![Standardised GDPPC and its spatial lag using row-standardised queen weights.](Hands-on_Ex0501_files/figure-html/fig-moran-scatter-1.png){#fig-moran-scatter width=672}\n:::\n:::\n\n\nThe line through the origin has slope I because the weights sum to the number of counties. The lag is computed **after** standardising GDPPC; independently standardising the lag would change this slope relationship. Quadrants describe relative values, not local significance.\n\n# 5 Geary's C\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngeary_result <- geary.test(hunan$GDPPC, weights,\n                           alternative = \"greater\", randomisation = TRUE)\nset.seed(1234)\ngeary_sim <- geary.mc(hunan$GDPPC, weights, nsim = 999,\n                      alternative = \"greater\")\ngeary_result\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tGeary C test under randomisation\n\ndata:  hunan$GDPPC \nweights: weights   \n\nGeary C statistic standard deviate = 3.6108, p-value = 0.0001526\nalternative hypothesis: Expectation greater than statistic\nsample estimates:\nGeary C statistic       Expectation          Variance \n        0.6907223         1.0000000         0.0073364 \n```\n\n\n:::\n\n```{.r .cell-code}\ngeary_sim\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Geary C\n\ndata:  hunan$GDPPC \nweights: weights  \nnumber of simulations + 1: 1000 \n\nstatistic = 0.69072, observed rank = 1, p-value = 0.001\nalternative hypothesis: greater\n```\n\n\n:::\n:::\n\n\nGeary's C uses squared differences between neighbours. Its null reference is one; smaller values indicate positive association. Here C is **0.6907** with permutation p = **0.001**. In these spdep functions, `alternative = \"greater\"` means greater positive autocorrelation, corresponding to the **lower** tail of C.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data.frame(C = geary_sim$res[seq_len(999)]), aes(C)) +\n  geom_histogram(bins = 25, fill = \"#4d9d88\", colour = \"white\") +\n  geom_vline(xintercept = unname(geary_sim$statistic), colour = \"#b2182b\", linewidth = 1) +\n  geom_vline(xintercept = 1, linetype = \"dashed\") +\n  labs(x = \"Geary's C under random reassignment\", y = \"Permutations\")\n```\n\n::: {.cell-output-display}\n![Permutation distribution of Geary's C; the observed value is red and the null reference of one is dashed.](Hands-on_Ex0501_files/figure-html/fig-geary-null-1.png){#fig-geary-null width=672}\n:::\n:::\n\n\n# 6 Spatial correlograms\n\nA lag here is a step in the county neighbour graph, not a kilometre distance or a time interval. Higher-order neighbours are defined by their shortest graph path.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmi_corr <- sp.correlogram(queen, hunan$GDPPC, order = 6,\n                         method = \"I\", style = \"W\", zero.policy = TRUE)\ngc_corr <- sp.correlogram(queen, hunan$GDPPC, order = 6,\n                         method = \"C\", style = \"W\", zero.policy = TRUE)\nprint(mi_corr, p.adj.method = \"holm\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatial correlogram for hunan$GDPPC \nmethod: Moran's I\n         estimate expectation   variance standard deviate Pr(I) two sided    \n1 (88)  0.3007500  -0.0114943  0.0043484           4.7351       1.217e-05 ***\n2 (88)  0.2060084  -0.0114943  0.0020962           4.7505       1.217e-05 ***\n3 (88)  0.0668273  -0.0114943  0.0014602           2.0496       0.0808001 .  \n4 (88)  0.0299470  -0.0114943  0.0011717           1.2107       0.2260150    \n5 (88) -0.1530471  -0.0114943  0.0012440          -4.0134       0.0002394 ***\n6 (88) -0.1187070  -0.0114943  0.0016791          -2.6164       0.0266570 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(gc_corr, p.adj.method = \"holm\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatial correlogram for hunan$GDPPC \nmethod: Geary's C\n        estimate expectation  variance standard deviate Pr(I) two sided   \n1 (88) 0.6907223   1.0000000 0.0073364          -3.6108        0.001831 **\n2 (88) 0.7630197   1.0000000 0.0049126          -3.3811        0.003610 **\n3 (88) 0.9397299   1.0000000 0.0049005          -0.8610        0.930122   \n4 (88) 1.0098462   1.0000000 0.0039631           0.1564        0.930122   \n5 (88) 1.2008204   1.0000000 0.0035568           3.3673        0.003610 **\n6 (88) 1.0773386   1.0000000 0.0058042           1.0151        0.930122   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(mfrow = c(1, 2))\nplot(mi_corr, main = \"Moran's I\")\nplot(gc_corr, main = \"Geary's C\")\npar(mfrow = c(1, 1))\n```\n\n::: {.cell-output-display}\n![Moran and Geary summaries across six graph lags.](Hands-on_Ex0501_files/figure-html/fig-correlograms-1.png){#fig-correlograms width=960}\n:::\n:::\n\n\nRead the estimates together with the printed tests. Holm adjustment is applied separately to the six lags for each statistic; it is an exploratory check, not a correction for every decision in this exercise. Associations at wider graph lags can differ from immediate-neighbour association. The plot's uncertainty bars are not simultaneous confidence bands.\n\n# 7 Interpretation and limitations\n\nThe main queen-weight tests give I = **0.301** and C = **0.691**, both consistent with positive spatial association in this dataset. The result describes relative county GDPPC patterns in **2012**, not changes through time. The analysis cannot establish spillover effects, causal mechanisms or local significance. County aggregation, unusually large indicator values and the province boundary can affect the summaries. Local analysis follows in [Exercise 5(2)](Hands-on_Ex0502.qmd).\n\n# References and session information\n\n- [Chapter 9: Global Measures of Spatial Autocorrelation](https://r4gdsa.netlify.app/chap09.html).\n- [spdep: Moran's I](https://r-spatial.github.io/spdep/reference/moran.test.html), [Geary's C](https://r-spatial.github.io/spdep/reference/geary.test.html), and [correlograms](https://r-spatial.github.io/spdep/reference/sp.correlogram.html).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR version 4.5.3 (2026-03-11 ucrt)\nPlatform: x86_64-w64-mingw32/x64\nRunning under: Windows 11 x64 (build 26200)\n\nMatrix products: default\n  LAPACK version 3.12.1\n\nlocale:\n[1] LC_COLLATE=English_United States.utf8 \n[2] LC_CTYPE=English_United States.utf8   \n[3] LC_MONETARY=English_United States.utf8\n[4] LC_NUMERIC=C                          \n[5] LC_TIME=English_United States.utf8    \n\ntime zone: Asia/Singapore\ntzcode source: internal\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n[1] knitr_1.51    ggplot2_4.0.3 readr_2.2.0   dplyr_1.2.1   tmap_4.4     \n[6] spdep_1.4-2   spData_2.3.5  sf_1.1-0     \n\nloaded via a namespace (and not attached):\n [1] tidyselect_1.2.1      farver_2.1.2          S7_0.2.2             \n [4] fastmap_1.2.0         leaflegend_1.2.8      leaflet_2.2.3        \n [7] TH.data_1.1-5         XML_3.99-0.23         digest_0.6.39        \n[10] lifecycle_1.0.5       LearnBayes_2.15.2     survival_3.8-6       \n[13] terra_1.9-27          magrittr_2.0.5        compiler_4.5.3       \n[16] rlang_1.2.0           tools_4.5.3           igraph_2.3.1         \n[19] yaml_2.3.12           data.table_1.18.2.1   labeling_0.4.3       \n[22] htmlwidgets_1.6.4     bit_4.6.0             sp_2.2-1             \n[25] classInt_0.4-11       RColorBrewer_1.1-3    multcomp_1.4-32      \n[28] abind_1.4-8           KernSmooth_2.23-26    withr_3.0.2          \n[31] leafsync_0.1.0        grid_4.5.3            cols4all_0.10        \n[34] e1071_1.7-17          leafem_0.2.5          colorspace_2.1-2     \n[37] spacesXYZ_1.6-0       MASS_7.3-65           scales_1.4.0         \n[40] mvtnorm_1.3-7         cli_3.6.6             rmarkdown_2.31       \n[43] crayon_1.5.3          generics_0.1.4        otel_0.2.0           \n[46] tzdb_0.5.0            tmaptools_3.3         DBI_1.3.0            \n[49] proxy_0.4-29          splines_4.5.3         spatialreg_1.4-3     \n[52] stars_0.7-2           parallel_4.5.3        s2_1.1.9             \n[55] marginaleffects_1.0.0 base64enc_0.1-6       vctrs_0.7.3          \n[58] sandwich_3.1-3        boot_1.3-32           Matrix_1.7-4         \n[61] jsonlite_2.0.0        hms_1.1.4             bit64_4.8.0          \n[64] crosstalk_1.2.2       units_1.0-1           maptiles_0.11.0      \n[67] glue_1.8.1            lwgeom_0.2-16         codetools_0.2-20     \n[70] gtable_0.3.6          deldir_2.0-4          raster_3.6-32        \n[73] tibble_3.3.1          logger_0.4.2          pillar_1.11.1        \n[76] htmltools_0.5.9       R6_2.6.1              wk_0.9.5             \n[79] microbenchmark_1.5.0  vroom_1.7.1           evaluate_1.0.5       \n[82] lattice_0.22-9        backports_1.5.1       png_0.1-9            \n[85] class_7.3-23          Rcpp_1.1.1-1.1        nlme_3.1-168         \n[88] coda_0.19-4.1         xfun_0.57             zoo_1.8-15           \n[91] pkgconfig_2.0.3      \n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "Hands-on_Ex0501_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}